global:
  scrape_interval: 1s
  external_labels:
    monitor: 'cadence-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: # addresses to scrape
          - 'cadence:9090'
          - 'cadence:8000'
          - 'cadence:8001'
          - 'cadence:8002'
          - 'cadence:8003'
          - 'host.docker.internal:8004' # Cadence shard distributor metrics exposed on host
          - 'host.docker.internal:9098' # Shard distributor canary metrics exposed on host
